### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by Niharika29** [Wikifab/UsersWatchlist#1]
Hi, I cloned this to http://commtech.wmflabs.org to play around with it but it gets stuck in a redirect loop between http://commtech.wmflabs.org/wiki/Special:FollowList and http://commtech.wmflabs.org/wiki/Special:Followlist

Thanks for looking into this.

**Comment by ricordisamoa** [comment]
#2 should fix it

**Comment by Niharika29** [comment]
Thanks, @ricordisamoa. Very much appreciated.

**Comment by Niharika29** [comment]
@ricordisamoa I made the edit on my local instance and I see an error "$this is null". I presume this refers to the $this in one/both of the Special pages. Do you have any idea what could be causing this?
Thanks.

**Comment by ricordisamoa** [comment]
@Niharika29 I get `Deprecated: Non-static method ChangesListSpecialPage::makeLegend() should not be called statically, assuming $this from incompatible context`. #3 should fix it, thank you.
